BEAT0SRC ;ALB/CJM - AICS LIST CLINIC SETUP ; JUL 20,1993
 ;;3.0;AUTOMATED INFO COLLECTION SYS;;APR 24, 1997
 ;
SETUPS ; -- Lists forms/reports defined in print manager clinic setup
 ;
% N CLINIC,SETUP,NODE,COND,INTRFACE,PAGE,IBQUIT,IBHDT,X,Y,FORM,REPORT,NAME,VAUTD,DIVIS,NEWDIV,CNT,MULTI
 W !!,"AICS Print Manager Clinic Setup Report",!!
 S IBQUIT=0
 D DIVIS G:IBQUIT EXIT
 D DEVICE G:IBQUIT EXIT
 D DQ
 G EXIT
 I $P($ZVER,"/",2)<4 ZN X ZNSPACE CURUCI Q X
 Q
 ;
