FINROU00 ; AU - FANIN TEST ; NOV 12,2012
 ;;3.0;TESTING;; NOV 12,2012
 ;
 Q
 ;
ADD(TARGET,SOURCE) ;
 S TARGET=TARGET+SOURCE
 Q
 ;
SUB(TARGET,SOURCE) ;
 S TARGET=TARGET-SOURCE
 Q
 ;
MULT(TARGET,SOURCE) ;
 S TARGET=TARGET*SOURCE
 Q
 ;
MULTADD(TARGET,SOURCE,SCALAR) ;
 D ADD(TARGET,SOURCE*SCALAR) 
